### ISSUE TITLE
Add support to the css `contain` property

### ISSUE THREAD

**Issue by equinusocio** [MhMadHamster/vscode-postcss-language#10]
`contain` property is marked as unknown property.

**Specs:**
- https://drafts.csswg.org/css-containment/

**Other links:**
- https://developer.mozilla.org/en-US/docs/Web/CSS/contain
- https://developers.google.com/web/fundamentals/getting-started/primers/shadowdom#containment

**Comment by MhMadHamster** [comment]
Hello, this plugin is using [https://github.com/Microsoft/vscode-css-languageservice](url) as a provider for rules and descriptions for them, so you probably should ask for it there.

**Comment by equinusocio** [comment]
Done https://github.com/Microsoft/vscode-css-languageservice/issues/31
