### ISSUE TITLE
@apply, @custom-media, @custom-selector throw errors

### ISSUE THREAD

**Issue by patrickfatrick** [MhMadHamster/vscode-postcss-language#11]
These are new specs supported by cssnext, but are flagged by the extension.

See http://cssnext.io/features/#custom-properties-set-apply, http://cssnext.io/features/#custom-media-queries, and http://cssnext.io/features/#custom-selectors

If there's an option to turn off the linting support that would also be fine with me because I'm usually using stylelint with postcss  anyway.

**Comment by MhMadHamster** [comment]
you can add `"postcss.validate": false` in config file to turn off validation

**Comment by patrickfatrick** [comment]
Perfect, that works.

**Comment by patrickfatrick** [comment]
Closing.
