### ISSUE TITLE
Sex mod! add formatting?

### ISSUE THREAD

**Issue by nihiluis** [MhMadHamster/vscode-postcss-language#12]
sex mod very nice

can I add formatting functionality to it somehow? imagine SASS mod

**Comment by MhMadHamster** [comment]
Hello,
Sorry but i don't quite understand what do you mean by formatting? like auto-formatting? there're plugins such as [beautify](https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify) for that.

**Comment by nihiluis** [comment]
CTRL + SHIFT + I is a format document shortcut. It's disabled if you enable PostCSS syntax.

**Comment by MhMadHamster** [comment]
ok, understood, will look into this when i'll have some free time

**Comment by tohuw** [comment]
Ok, not gonna lie. I seriously thought this was a spam comment when I read the title.

**Comment by levinit** [comment]
> CTRL + SHIFT + I is a format document shortcut. It's disabled if you enable PostCSS syntax.

some problem, can not format if enable postcss syntax
