### ISSUE TITLE
Add support for cssnext

### ISSUE THREAD

**Issue by rafalschmidt97** [MhMadHamster/vscode-postcss-language#15]
Hi,
Do you plan to add support for cssnext? More exacly I need http://cssnext.io/features/#custom-media-queries.

**Comment by MhMadHamster** [comment]
Hello,
the short answer is no, an explanation "why" can be found [here](https://github.com/MhMadHamster/vscode-postcss-language/issues/14#issuecomment-321522022)

**Comment by onetrev** [comment]
Good news @rshmiraf -- support for cssnext is planned for the new round of updates for VS Code. More details here in the CSS/HTML section: https://github.com/Microsoft/vscode/issues/41061
