### ISSUE TITLE
Emmet abbreviations in 1.15.1

### ISSUE THREAD

**Issue by Nejik** [MhMadHamster/vscode-postcss-language#16]
Hi! Thanks for this plugin. Seems bug related to #3 and #4.
In postcss language and VS CODE 1.15.1 color square and autocomplete working good, but not emmet abbreviations :( 
In usual css/less/sass language all fine. Can we fix that somehow?

**Comment by MhMadHamster** [comment]
Hello, try adding `"emmet.includeLanguages": { "postcss": "css" }` to your settings in vscode and let me know if it has worked out for you.

**Comment by Nejik** [comment]
unfortunately doesnt help :(
In your environment emmet working normal with postcsss syntax?

**Comment by Nejik** [comment]
Hm, after second redactor restart its working, thank you!)
