### ISSUE TITLE
Don't use PostCSS icon for `.css` files

### ISSUE THREAD

**Issue by svipas** [MhMadHamster/vscode-postcss-language#2]
Hello,

I think it's better to turn off by default `.css` icons, because I like to use this plugin https://marketplace.visualstudio.com/items?itemName=robertohuertasm.vscode-icons which have really good icons for VS Code and right now my `.css` files look like this:

![screenshot from 2017-04-30 23-30-16](https://cloud.githubusercontent.com/assets/10441177/25567730/06eb104e-2dfd-11e7-909e-4759f9f8e916.png)

So my suggestion is to turn off by default icons for `.css` files and let people decide if they want use it.

File: `.css`.
VS Code: 1.11
OS: Linux Ubuntu 16.04

P.S. Tested, seems this happens only with this https://marketplace.visualstudio.com/items?itemName=robertohuertasm.vscode-icons enabled.

**Comment by withrvr** [comment]
same bro
for .css files i want .css icons
not of postcss icons


how do I change it
for 1 hour I am finding out on the internet 
no solutions for this 


how I change the .css icon to CSS ... not postcss icon

**Comment by soorajkj** [comment]
@withrvr @svipas
