### ISSUE TITLE
Extension breaks autocomplete options

### ISSUE THREAD

**Issue by pietrofxq** [MhMadHamster/vscode-postcss-language#21]
Using this extension, I don't see the values in the autocomplete for css properties anymore.

Expected behavior:

![image](https://user-images.githubusercontent.com/6238029/35187579-454887e6-fe0d-11e7-920d-3f812532b640.png)

Actual behavior:

![image](https://user-images.githubusercontent.com/6238029/35187582-50732806-fe0d-11e7-999a-a2b4cd1a13ac.png)

**Comment by MhMadHamster** [comment]
should work in 2.1 thanks to #26
