### ISSUE TITLE
allow mixins

### ISSUE THREAD

**Issue by mauricekraus** [MhMadHamster/vscode-postcss-language#22]
Hi,
would it be possible to allow mixins ?

**Comment by MhMadHamster** [comment]
hello, if you mean validation error just add `"postcss.validate": false` in your settings

**Comment by mauricekraus** [comment]
well but is your syntax highlighter not useless afterwards ?

**Comment by MhMadHamster** [comment]
it's meant to highlight syntax, not to validate it, and the validation which currently works is wrong because it's postcss and you can't validate it without knowing what plugins exactly user is using.
