### ISSUE TITLE
Syntax uses // instead of /* */ as comment

### ISSUE THREAD

**Issue by pietrofxq** [MhMadHamster/vscode-postcss-language#23]
When using the postcss syntax, the command `Toggle Line Comment` adds a commentary to the css line using two slashes: 

![image](https://user-images.githubusercontent.com/6238029/35415012-5781ff08-020b-11e8-9db7-d7aff21165ce.png)

This syntax is from SASS commentaries, so this extension should add a comment with the original css syntax:

![image](https://user-images.githubusercontent.com/6238029/35415061-7eb43e1a-020b-11e8-86a0-2cdaca1513d2.png)

**Comment by Manc** [comment]
Looks like there is already a closed ticket #20 and a merged solution #17, but it looks like it's not been published yet. I was looking for a way to override this via the config, but didn't find a solution.

**Comment by MhMadHamster** [comment]
new version published

**Comment by reblws** [comment]
Hey I'm still getting this issue in VSCode. Does this need to be configured?

**Comment by MhMadHamster** [comment]
@reblws what version are you using? and what file extension, I just tested the latest version and it works how it should.

**Comment by reblws** [comment]
I'm on 2.1.0 -- the extension under `postcss-sugarss-language` in the VSCode marketplace. 

Using `.css` extension. I didn't change "files.associations" in mysettings but I did manually set "Language Mode" to PostCSS.

**Comment by reblws** [comment]
I checked my `mhmadhamster.postcss-language-2.1.0/configurations/language-configuration.json` and it's the same as the change referenced in #17:

```
{
    "comments": {
        // symbols used for start and end a block comment. Remove this entry if your language does not support block comments
        "blockComment": [ "/*", "*/" ]
    },
    // symbols used as brackets
    "brackets": [
        ["{", "}"],
        ["[", "]"],
        ["(", ")"]
    ],
    // symbols that are auto closed when typing
    "autoClosingPairs": [
        ["{", "}"],
        ["[", "]"],
        ["(", ")"],
        ["\"", "\""],
        ["'", "'"]
    ],
    // symbols that that can be used to surround a selection
    "surroundingPairs": [
        ["{", "}"],
        ["[", "]"],
        ["(", ")"],
        ["\"", "\""],
        ["'", "'"]
    ]
}
```

**Comment by reblws** [comment]
I realized that if I hit the shortcut for `Toggle Block Comment` it uses the right symbols. I was hitting the shortcut for `Toggle Line Comment` before.

It's a little confusing since hitting `Toggle Line Comment` outputs `//`, but in the default CSS language settings `Toggle Line Comment` outputs `/* */`
