### ISSUE TITLE
Add autocomplete support for nested rules

### ISSUE THREAD

**Issue by pietrofxq** [MhMadHamster/vscode-postcss-language#24]
I'm currently using `postcss-nested`, but this is valid for cssnext nesting features too.

When a rule is nested, the autocomplete only display values for pseudo-classes:

![image](https://user-images.githubusercontent.com/6238029/35488020-ab9e381c-0469-11e8-996e-24e48ecd9472.png)

**Comment by MhMadHamster** [comment]
should work in 2.1 thanks to #26
