### ISSUE TITLE
Doesn't show color box

### ISSUE THREAD

**Issue by svipas** [MhMadHamster/vscode-postcss-language#3]
Hello,

with this plugin enabled I can't see color box like this:

![screenshot from 2017-04-30 23-35-00](https://cloud.githubusercontent.com/assets/10441177/25567764/b43ace24-2dfd-11e7-91b2-b75980782b82.png)

With plugin enabled it disappears.

File: `.css`.
VS Code: 1.11
OS: Linux Ubuntu 16.04

**Comment by svipas** [comment]
This https://github.com/MhMadHamster/vscode-postcss-language/issues/4 is related, it's because of language mode. Disappears autocomplete and color box.

**Comment by MhMadHamster** [comment]
fixed in version 2.0

**Comment by a1mersnow** [comment]
still not work?
