### ISSUE TITLE
Does not respect CSS/SCSS validate setting

### ISSUE THREAD

**Issue by chrishoage** [MhMadHamster/vscode-postcss-language#5]
I use Stylelint in a project with Postcss which defines some non-standard css properties and rules. 

In my workspace settings I have 

```
  "css.validate": false,
  "scss.validate": false
```

Which is supposed to suppress validation warnings for css and scss. When I have this plugin installed with 

```
  "files.associations": {
    "*.css": "postcss"
  }
```

I can not disable the warnings

![screen shot 2017-05-07 at 3 15 06 pm](https://cloud.githubusercontent.com/assets/1056886/25785534/01a220a6-3338-11e7-87ae-296ca373f93e.png)

Is it possible to turn off the validation while retaining auto complete?

**Comment by MhMadHamster** [comment]
Hey @chrishoage i just published new version, you can now add `"postcss.validate": false` in your vscode settings file to turn off validation for postcss

**Comment by chrishoage** [comment]
This works as expected, super big thanks for the quick turn around time and a PostCSS plugin that works with Intellesense. 

You rock!
