### ISSUE TITLE
Feature request: styled-jsx-postcss support

### ISSUE THREAD

**Issue by comerc** [MhMadHamster/vscode-postcss-language#6]
Please add support of [styled-jsx-postcss](https://github.com/giuseppeg/styled-jsx-postcss).

[Example app with styled-jsx-postcss](https://github.com/zeit/next.js/tree/master/examples/with-styled-jsx-postcss):
```jsx
export default () => (
  <div className='hello'>
    <p>Hello World</p>
    <style jsx>{`
      :global(:root) {
        --bgColor: green;
        --color: white;
      }
      .hello {
        font: 15px Helvetica, Arial, sans-serif;
        background: var(--bgColor);
        color: var(--color);
        padding: 100px;
        text-align: center;
        transition: 100ms ease-in background;
      }
      .hello:hover {
        color: color(var(--color) blackness(+80%));
      }
    `}</style>
  </div>
)
```

Also we have [vscode-styled-jsx](https://github.com/xekri/vscode-styled-jsx) without support of postcss.

**Comment by MhMadHamster** [comment]
Hello, i just published new version, check it out, should work out for styled jsx now as well, but without intellisense and color decorators

**Comment by comerc** [comment]
Thanks. It is work fine! But now I want more features: intellisense and color decorators. :)

Also I found bug when press [CTRL]+[/] - JSX-comment instead of CSS-comment:
```jsx
<style jsx>{`
  {/*.hello { color: red }*/}
`}</style>
```

**Comment by MhMadHamster** [comment]
Closing since main issue (i.e. syntax support for styled jsx) was solved and for the other ones i opened separate issues
